# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute
# config/routes.yaml
# api/config/routes.yaml
auth:
    path: /auth
    methods: ['POST']